import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './components/provider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = getServerSession(authOptions)


  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider session={session}>{children}</Provider>
      </body>
    </html>
  )
}
